# Site settings
title:          Игорь Постольный
description:    "И. А. Постольный – литературные и музыкальные сочинения • Итальянский язык"
baseurl:        ""
url:            "https://postolny.github.io"

defaults:
  - scope:
      path: ""
    values:
      image:     /assets/Rome-Parco-degli-Acquedotti1200x627.jpg

# Google Analytics
google_analytics:

# Author
author:
  name:         Игорь Постольный
  url:          
  email:        

# Build settings
markdown: kramdown  # Используется движок Kramdown для обработки Markdown
kramdown:
  input: GFM  # Используется синтаксис GitHub Flavored Markdown
  syntax_highlighter: rouge  # Подсветка синтаксиса с помощью Rouge
  syntax_highlighter_opts:
    line_numbers: true  # Включить нумерацию строк
    start_line: 1  # Начало нумерации с первой строки
  smart_quotes: ["apos", "apos", "quot", "quot"]  # Настройки "умных кавычек"

include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
seo_paginator_message: "Страница %<current>s | "

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:
 
locale: ""